Add IdentityServer events to AdapterFactory
RockSolidKnowledge/Audit pull request #5
Opened 2022-02-22 11:04 UTC by RaheelRsk

2022-02-22 12:19 UTC, rehcra22 approved these changes
:shipit:

2022-03-08 15:02 UTC, SundasChoudyRsk requested changes

2022-03-10 14:29 UTC, SundasChoudyRsk commented on src/Rsk.DuendeIdentityServer.AuditEventSink/Adapters/UnhandledExceptionEventAdapter.cs
> +        public ResourceActor Actor => new ResourceActor(ResourceActor.MachineSubjectType, evt.ActivityId, evt.Details);
Here, I don't there's any actor. Can we set actor identifier and displayName as null or an empty string maybe? I don't think the event has any properties on it that could determine the actor.

2022-03-10 14:29 UTC, SundasChoudyRsk commented on src/Rsk.DuendeIdentityServer.AuditEventSink/Adapters/TokenRevokedSuccessEventAdapter.cs
> +        public AuditableResource Resource => new AuditableResource("IdentityServer", evt.ClientId);
The event has a property called `TokenType`, we can set the AuditableResource Identifier to this

2022-03-10 14:29 UTC, SundasChoudyRsk commented on src/Rsk.DuendeIdentityServer.AuditEventSink/Adapters/TokenIntrospectionSuccessEventAdapter.cs
> +        public AuditableResource Resource => new AuditableResource("IdentityServer", evt.ActivityId);
Here, the resource AuditableResource identifier can be `evt.ApiName`

2022-03-10 14:29 UTC, SundasChoudyRsk commented on src/Rsk.DuendeIdentityServer.AuditEventSink/Adapters/TokenIntrospectionSuccessEventAdapter.cs
> +        public ResourceActor Actor => new ResourceActor(ResourceActor.UserSubjectType, evt.ActivityId, evt.ApiName);
Here, I don't think we have a Resource Actor identifier. Should this be null or empty?

2022-03-10 14:29 UTC, SundasChoudyRsk commented on src/Rsk.DuendeIdentityServer.AuditEventSink/Adapters/TokenIntrospectionFailureEventAdapter.cs
> +        public AuditableResource Resource => new AuditableResource("IdentityServer", evt.ActivityId);
The AuditableResource should be `evt.ApiName`

2022-03-10 14:29 UTC, SundasChoudyRsk commented on src/Rsk.DuendeIdentityServer.AuditEventSink/Adapters/TokenIntrospectionFailureEventAdapter.cs
> +        public ResourceActor Actor => new ResourceActor(ResourceActor.UserSubjectType, evt.ActivityId, evt.ApiName);
Again here, there's not subject

2022-03-10 15:45 UTC, SundasChoudyRsk approved these changes

2022-03-11 08:10 UTC, merged